TasmSite/Controllers/DeviceGroupController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TasmSite.Models;

namespace TasmSite.Controllers
{
    /// <summary>
    /// Handles the User input from the view, handles request and makes changes to the DeviceGroup model
    /// </summary>
    public class DeviceGroupController : Controller
    {
        private TasmEntities db = new TasmEntities();

        // GET: DeviceGroup
        public ActionResult Index()
        {
            var deviceGroups = db.DeviceGroups.Include(d => d.DeviceGroup2);
            return View(deviceGroups.ToList());
        }

        /// <summary>
        /// retrieves the details of the DeviceGroup of the specified id
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Details view for the DeviceGroup of the specified id</returns>
        // HTTP GET request: DeviceGroup/Details/{id}
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeviceGroup deviceGroup = db.DeviceGroups.Find(id);
            if (deviceGroup == null)
            {
                return HttpNotFound();
            }
            return View(deviceGroup);
        }

        // GET: DeviceGroup/Create
        public ActionResult Create()
        {
            ViewBag.ParentGroupId = new SelectList(db.DeviceGroups, "Id", "Name");
            return View();
        }

        // POST: DeviceGroup/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ParentGroupId")] DeviceGroup deviceGroup)
        {
            if (ModelState.IsValid)
            {
                db.DeviceGroups.Add(deviceGroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ParentGroupId = new SelectList(db.DeviceGroups, "Id", "Name", deviceGroup.ParentGroupId);
            return View(deviceGroup);
        }

        // GET: DeviceGroup/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeviceGroup deviceGroup = db.DeviceGroups.Find(id);
            if (deviceGroup == null)
            {
                return HttpNotFound();
            }
            ViewBag.ParentGroupId = new SelectList(db.DeviceGroups, "Id", "Name", deviceGroup.ParentGroupId);
            return View(deviceGroup);
        }

        // POST: DeviceGroup/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ParentGroupId")] DeviceGroup deviceGroup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deviceGroup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ParentGroupId = new SelectList(db.DeviceGroups, "Id", "Name", deviceGroup.ParentGroupId);
            return View(deviceGroup);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TasmSite/Controllers/FirmwareController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TasmSite.Models;

namespace TasmSite.Controllers
{
    /// <summary>
    /// Handles the User input from the view, handles request and makes changes to the Firmware model
    /// </summary>
    public class FirmwareController : Controller
    {
        private TasmEntities db = new TasmEntities();

        // GET: Firmware
        public ActionResult Index()
        {
            var firmwares = db.Firmwares.Include(f => f.Firmware2);
            return View(firmwares.ToList());
        }

        /// <summary>
        /// retrieves the details of the Firmware of the specified id
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Details view for the Firmware of the specified id</returns>
        // HTTP GET request: DeviceGroup/Details/{id}
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Firmware firmware = db.Firmwares.Find(id);
            if (firmware == null)
            {
                return HttpNotFound();
            }
            return View(firmware);
        }

        // GET: Firmware/Create
        public ActionResult Create()
        {
            ViewBag.PreviousId = new SelectList(db.Firmwares, "Id", "Name");
            return View();
        }

        // POST: Firmware/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Version,ReleaseDate,PreviousId")] Firmware firmware)
        {
            if (ModelState.IsValid)
            {
                db.Firmwares.Add(firmware);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PreviousId = new SelectList(db.Firmwares, "Id", "Name", firmware.PreviousId);
            return View(firmware);
        }

        // GET: Firmware/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Firmware firmware = db.Firmwares.Find(id);
            if (firmware == null)
            {
                return HttpNotFound();
            }
            ViewBag.PreviousId = new SelectList(db.Firmwares, "Id", "Name", firmware.PreviousId);
            return View(firmware);
        }

        // POST: Firmware/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Version,ReleaseDate,PreviousId")] Firmware firmware)
        {
            if (ModelState.IsValid)
            {
                db.Entry(firmware).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PreviousId = new SelectList(db.Firmwares, "Id", "Name", firmware.PreviousId);
            return View(firmware);
        }

        // GET: Firmware/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Firmware firmware = db.Firmwares.Find(id);
            if (firmware == null)
            {
                return HttpNotFound();
            }
            return View(firmware);
        }

        // POST: Firmware/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Firmware firmware = db.Firmwares.Find(id);
            int nextId = id;
            if (firmware.Firmware1.Any())
            {
                nextId = firmware.Firmware1.ElementAt(0).Id;
            }
            else if (firmware.PreviousId != null)
            {
                nextId = (int)firmware.PreviousId;
            }
            var devices = db.Devices.Where(d => d.FirmwareId == id);
            foreach (Device device in devices)
            {
                device.FirmwareId = nextId;
            }
            db.SaveChanges();
            db.Firmwares.Remove(firmware);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TasmSite/Controllers/HomeController.cs
using System.Web.Mvc;

namespace TasmSite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Our Journey";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact Information";

            return View();
        }
    }
}

TasmSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title</h2>
    <h3 class="HomeSubTitle">@ViewBag.Message</h3>

    <p>TASM (Tracking Assest & Sensor Monitoring) was founded in Cape Town in 2024. The owner was tired or not being able to find
    is heys and wallet so decided to to create small trackers he could attach to his keychain and wallet. Now with a user friendly
    mobile and web application he could find his possessions inside his own home. <br />
    This didn't end there as he started to develop his own trackers for his car and his dogs' dog collar. He later expanded into
    temperature, pressure & light sensors for various devices and purpose.</p>

    <h3 class="HomeSubTitle">Values</h3>
    <ol>
        <li>Innovation: Use the latest technology to design new devices</li>
        <li>Growth: Hiring more engineers and developers</li>
        <li>Give Back: Make a difference to our environment and those around us</li>
    </ol>

    <h3 class="HomeSubTitle">Company Culture</h3>
    <p> We have a very vibrant and relaxed culture at our workplace. There is a "chill room" with a foosball and pool table.
    pointy shoes and button ups are optional. We have annual staff retreats and quarterly functions. This is a great place learn
    and develop your skills. We are big on health as we participate on hikes and indoor football monthly. We care for our workers
    and make sure they medical aid is covered.</p>
</main>

TasmSite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Page";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title</h2>
    <h3 class="HomeSubTitle" style="margin-left:15%; margin-right:auto">
        @ViewBag.Message
    </h3>

    <div class="sideBySide">
        <div style="margin-left:15%; margin-right:auto">
            <address>
                Contact us at the following:
                <ul>
                    <li><strong>Email:</strong><a href="mailto:sihlecalana@gmail.com">Support@example.com</a></li>
                    <li><strong>Telephone:</strong> 021 6785 0505</li>
                    <li><strong>Address:</strong> 1 Place St, Suburb</li>
                </ul>
            </address>
        </div>

        <div style="margin-left:auto; margin-right:15%">
            <form>
                <h6>Want Us To Contact You?</h6>
                <input type="text" placeholder="Name" autofocus>
                <input type="email" placeholder="Email Address">
                <input type="tel" placeholder="Phone No.: xxx xxx xxxx" pattern="[0-9]{3} [0-9]{3} [0-9]{4}" required><br>
                <textarea placeholder="What is your query?" class="box"></textarea>
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
</main>

TasmSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">TASM - Tracking & Monitoring Devices</h1>
        <p class="lead">TASM is a proudly South African compny that offers a
        wide range of Asset tracking and asset monitoring devices, produced by the most innovative minds! Excellence is
        at the core of our values ever since we were founded.</p>
        <p><a href="@Url.Action("About","Home")" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="HomeSubTitle">
            <h2 class="HomeSubTitle">Devices Range</h2>
            <p>
                We provide a wide range of asset tracking and sensor monitoring devices that can be used in almost any environment.
                Whether its for monitoring driving safety, household smart meters, livestock location tracking, poaching prevention
                and much more. Our devices are tailored for various occasions, be it indoors or outdoors.
            </p>
            <p><a class="btn btn-outline-dark" href="@Url.Action("Index","DeviceGroup")">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="HomeSubTitle">
            <h2 class="HomeSubTitle">Firmware Support</h2>
            <p>Find out the different firmware used by our devices and which firmware each of our devices use</p>
            <p><a class="btn btn-outline-dark" href="@Url.Action("Index","Firmware")">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="HomeSubTitle">
            <h2 class="HomeSubTitle">Reach Us</h2>
            <p>Want to contact us or you want us? Find our details on the contact page or fill in the form and we
            shall get back to you!</p>
            <p><a class="btn btn-outline-dark" href="@Url.Action("Contact","Home")">Learn more &raquo;</a></p>
        </section>
    </div>
</main>